# Generated by Django 6.0 on 2025-12-22 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEMANDE', 'Demander un emploi'), ('OFFRE', 'Offrir un emploi')], db_index=True, max_length=10)),
                ('titre', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('adresse', models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('telephone', models.CharField(db_index=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Téléphone invalide. Format attendu: +221771234567 ou 771234567 (8 à 15 chiffres).', regex='^\\+?\\d{8,15}$')])),
                ('est_approuvee', models.BooleanField(db_index=True, default=False)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('score_recherche', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=230)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='catalog.jobcategory')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'indexes': [models.Index(fields=['est_approuvee', '-cree_le'], name='annonces_an_est_app_9b9825_idx'), models.Index(fields=['categorie', 'est_approuvee'], name='annonces_an_categor_2f9a7d_idx'), models.Index(fields=['type', 'est_approuvee'], name='annonces_an_type_680fd4_idx')],
            },
        ),
    ]
