# Generated by Django 6.0 on 2025-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_whatsappotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappotp',
            options={'verbose_name': 'OTP WhatsApp'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client / Particulier'), ('PRO', 'Professionnel / Prestataire'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_verified',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Vérifié'),
        ),
        migrations.AlterField(
            model_name='whatsappotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='whatsappotp',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
