# Generated by Django 6.0 on 2025-12-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('call_phone', models.CharField(max_length=32)),
                ('whatsapp_phone', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pros/avatars/')),
                ('online_status', models.CharField(choices=[('ONLINE', 'En ligne'), ('OFFLINE', 'Hors service')], default='ONLINE', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pros', to='catalog.job')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pros', to='catalog.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pros.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('CV', 'CV')], max_length=10)),
                ('file', models.FileField(upload_to='pros/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pros.professionalprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['job'], name='pros_profes_job_id_206d58_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['location'], name='pros_profes_locatio_729a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['is_published'], name='pros_profes_is_publ_d935f4_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['online_status'], name='pros_profes_online__5136e9_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritecontact',
            index=models.Index(fields=['owner'], name='pros_favori_owner_i_c95c07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecontact',
            unique_together={('owner', 'pro')},
        ),
        migrations.AddIndex(
            model_name='promedia',
            index=models.Index(fields=['pro', 'kind'], name='pros_promed_pro_id_56bd89_idx'),
        ),
    ]
