# Generated by Django 6.0 on 2025-12-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Favori',
                'verbose_name_plural': 'Contacts Favoris',
            },
        ),
        migrations.CreateModel(
            name='MediaPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('CV', 'CV')], max_length=10, verbose_name='Type de contenu')),
                ('fichier', models.FileField(upload_to='pros/media/', verbose_name='Fichier')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Média Professionnel',
                'verbose_name_plural': 'Médias Professionnels',
            },
        ),
        migrations.CreateModel(
            name='ProfilProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=160, verbose_name='Nom commercial')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('telephone_appel', models.CharField(max_length=32, verbose_name='Téléphone (Appel)')),
                ('telephone_whatsapp', models.CharField(max_length=32, verbose_name='Téléphone (WhatsApp)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pros/avatars/')),
                ('statut_en_ligne', models.CharField(choices=[('ONLINE', 'En ligne'), ('OFFLINE', 'Hors service')], default='ONLINE', max_length=10, verbose_name='Statut de disponibilité')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Est publié')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Profil Professionnel',
                'verbose_name_plural': 'Profils Professionnels',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritecontact',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='favoritecontact',
            name='pros_favori_owner_i_c95c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalprofile',
            name='pros_profes_job_id_206d58_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalprofile',
            name='pros_profes_locatio_729a8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalprofile',
            name='pros_profes_is_publ_d935f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalprofile',
            name='pros_profes_online__5136e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='promedia',
            name='pros_promed_pro_id_56bd89_idx',
        ),
        migrations.AddField(
            model_name='contactfavori',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur (Propriétaire)'),
        ),
        migrations.AddField(
            model_name='profilprofessionnel',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pros', to='catalog.job', verbose_name='Métier'),
        ),
        migrations.AddField(
            model_name='profilprofessionnel',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='profilprofessionnel',
            name='zone_geographique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pros', to='catalog.location', verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='mediapro',
            name='professionnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pros.profilprofessionnel', verbose_name='Profil professionnel'),
        ),
        migrations.AddField(
            model_name='contactfavori',
            name='professionnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pros.profilprofessionnel', verbose_name='Profil favorisé'),
        ),
        migrations.RemoveField(
            model_name='favoritecontact',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='favoritecontact',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promedia',
            name='pro',
        ),
        migrations.AddIndex(
            model_name='profilprofessionnel',
            index=models.Index(fields=['metier'], name='pros_profil_metier__07ab4a_idx'),
        ),
        migrations.AddIndex(
            model_name='profilprofessionnel',
            index=models.Index(fields=['zone_geographique'], name='pros_profil_zone_ge_a99044_idx'),
        ),
        migrations.AddIndex(
            model_name='profilprofessionnel',
            index=models.Index(fields=['est_publie'], name='pros_profil_est_pub_47516a_idx'),
        ),
        migrations.AddIndex(
            model_name='profilprofessionnel',
            index=models.Index(fields=['statut_en_ligne'], name='pros_profil_statut__2b8195_idx'),
        ),
        migrations.AddIndex(
            model_name='mediapro',
            index=models.Index(fields=['professionnel', 'type_media'], name='pros_mediap_profess_8525c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contactfavori',
            index=models.Index(fields=['proprietaire'], name='pros_contac_proprie_98f9e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactfavori',
            unique_together={('proprietaire', 'professionnel')},
        ),
        migrations.DeleteModel(
            name='FavoriteContact',
        ),
    ]
