# Generated by Django 6.0 on 2025-12-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('COMPORTEMENT_ABUSIF', 'Comportement abusif'), ('FRAUDE', 'Fraude ou Arnaque'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Raison du signalement')),
                ('message', models.TextField(blank=True, verbose_name='Message détaillé')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='moderation__status_3fc7e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='moderation__created_7bb7e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='moderation__profess_4cc10e_idx',
        ),
        migrations.AddField(
            model_name='signalement',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur'),
        ),
    ]
