# Generated by Django 6.0 on 2025-12-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='catalog.jobcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='catalog_job_categor_f85087_idx'), models.Index(fields=['is_featured'], name='catalog_job_is_feat_58bf36_idx'), models.Index(fields=['slug'], name='catalog_job_slug_f11d95_idx')],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('COUNTRY', 'Pays'), ('REGION', 'Région'), ('CITY', 'Ville'), ('DISTRICT', 'Quartier')], max_length=10)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.location')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='catalog_loc_type_6c8ab7_idx'), models.Index(fields=['parent'], name='catalog_loc_parent__737ae3_idx'), models.Index(fields=['slug'], name='catalog_loc_slug_88512d_idx')],
                'unique_together': {('parent', 'name', 'type')},
            },
        ),
    ]
